global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
    - targets: ['prometheus:9090']
   
  - job_name: 'node'
    static_configs:
    - targets: ['node_exporter:9100']
  # - job_name: 'windows'
  #   static_configs:
  #   - targets: ['<IP>:9182']

remote_write:
  - url: "http://prometheus:9100/metrics"
    basc_auth:
      username: admin
      password:


  
