server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions: 
  filename: /tmp/loki/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        name: varlogs
        job: varlogs
        __path__: /var/log/*log
    - targets:
        - localhost
      labels:
        name: zabbixlogs
        job: zabbixlogs
        __path__: /var/log/zabbix/*log
    
  